default:
  target: fabric
  outputs:
    fabric:
      type: fabric
      driver: "ODBC Driver 18 for SQL Server"
      workspace: dbt-dev-we
      database: demoprep
      schema: dbt_sam
      lakehouse: demopreplh
